Collectors.toMap
konsoletyper/teavm pull request #515
Opened 2020-07-11 15:02 UTC by Ihromant

2020-09-08 16:04 UTC, Ihromant commented
@konsoletyper what about this PR?

2020-10-07 09:07 UTC, konsoletyper requested changes

2020-10-07 09:07 UTC, konsoletyper commented on classlib/src/main/java/org/teavm/classlib/java/util/stream/TCollectors.java
> +                    m2.forEach((k, v) -> {
You better use `for` statement over map entries over `forEach`, since `forEach` produces extra overhead.

2020-10-07 09:07 UTC, konsoletyper commented on classlib/src/main/java/org/teavm/classlib/java/util/stream/TCollectors.java
> +                    m2.forEach((k, v) -> m1.merge(k, v, mergeFunction));
Please, use `for` statement here

2020-10-07 09:21 UTC, merged